version: "3.10"
services:
  prod_db:
    image: postgres:15.1-alpine
    container_name: prod_db
    env_file:
      - .env_prod
    healthcheck:
      test: /bin/bash -c "pg_isready -d prod_db -U someuser"
      interval: 10s
      timeout: 10s
      retries: 5

  prod_api:
    build:
      context: .
    container_name: prod_api
    env_file:
      - .env_prod
    ports:
      - 8000:8000
    depends_on:
      prod_db:
        condition: service_healthy
      redis:
        condition: service_healthy
    command: /bin/bash -c "python -m uvicorn menu_restaurant.main:app --reload --host 0.0.0.0 --port 8000"

  redis:
    image: redis:7
    container_name: redis
    env_file:
      - .env_prod
    depends_on:
      - prod_db
    healthcheck:
      test: /bin/bash -c "redis-cli ping"
      interval: 10s
      timeout: 3s
      retries: 3
