version: "3.10"
services:
  test_api:
    build:
      context: .
    container_name: test_api
    env_file:
      - .env_test_db
    depends_on:
      test_db:
        condition: service_healthy
      redis:
        condition: service_healthy
    command: /bin/bash -c "pytest -v"

  test_db:
    image: postgres:15.1-alpine
    container_name: test_db
    env_file:
      - .env_test_db
    healthcheck:
      test: /bin/bash -c "pg_isready -d test_db -U someuser"
      interval: 10s
      timeout: 10s
      retries: 5

  redis:
    image: redis:7
    container_name: redis
    env_file:
      - .env_test_db
    healthcheck:
      test: /bin/bash -c "redis-cli ping"
      interval: 10s
      timeout: 3s
      retries: 3
